import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtempSync, readFileSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { initSecrets, adminToken } from '../src/config.js';
import { DatabaseSync } from 'node:sqlite';
import { openDb } from '../src/db.js';
import { PagService } from '../src/service.js';
import { createServer } from '../src/server.js';

function fixture(){const dir=mkdtempSync(join(tmpdir(),'pag-test-'));initSecrets(dir);const db=openDb(dir);const service=new PagService(db,{dir});return{dir,db,service,cleanup(){db.close();rmSync(dir,{recursive:true,force:true})}}}

test('default deny blocks ungranted capabilities',async()=>{const f=fixture();try{const {actor}=f.service.createActor('agent');const intent=await f.service.createIntent({actorId:actor.id,capability:'noop.test',args:{a:1}});assert.equal(intent.status,'denied');assert.equal(intent.execution,null)}finally{f.cleanup()}});

test('ask grant binds approval to exact payload and executes once',async()=>{const f=fixture();try{const {actor}=f.service.createActor('agent');f.service.createGrant({actorId:actor.id,capability:'noop.test',effect:'ask'});const intent=await f.service.createIntent({actorId:actor.id,capability:'noop.test',args:{a:1},idempotencyKey:'k1'});assert.equal(intent.status,'pending_approval');assert.ok(intent.approval);await assert.rejects(()=>f.service.approve(intent.approval.id,{expectedArgsHash:'wrong'}),/hash mismatch/i);const done=await f.service.approve(intent.approval.id,{expectedArgsHash:intent.args_hash});assert.equal(done.status,'succeeded');assert.equal(done.execution.result.echo.a,1);const again=await f.service.approve(intent.approval.id,{expectedArgsHash:intent.args_hash});assert.equal(again.execution.id,done.execution.id);const count=f.db.prepare('SELECT COUNT(*) n FROM executions').get().n;assert.equal(Number(count),1)}finally{f.cleanup()}});

test('idempotency keys cannot be rebound to different payloads',async()=>{const f=fixture();try{const {actor}=f.service.createActor('agent');f.service.createGrant({actorId:actor.id,capability:'noop.test',effect:'allow'});const a=await f.service.createIntent({actorId:actor.id,capability:'noop.test',args:{a:1},idempotencyKey:'same'});const b=await f.service.createIntent({actorId:actor.id,capability:'noop.test',args:{a:1},idempotencyKey:'same'});assert.equal(a.id,b.id);await assert.rejects(()=>f.service.createIntent({actorId:actor.id,capability:'noop.test',args:{a:2},idempotencyKey:'same'}),/different arguments/i)}finally{f.cleanup()}});

test('deny at the highest matching priority wins over allow',async()=>{const f=fixture();try{const {actor}=f.service.createActor('agent');f.service.createGrant({actorId:actor.id,capability:'noop.*',effect:'allow',priority:10});f.service.createGrant({actorId:actor.id,capability:'noop.test',effect:'deny',priority:10});const i=await f.service.createIntent({actorId:actor.id,capability:'noop.test',args:{}});assert.equal(i.status,'denied')}finally{f.cleanup()}});

test('vault encrypts secrets and API metadata never returns plaintext',()=>{const f=fixture();try{f.service.vault.put('demo','super-secret-value',{connector:'noop'});assert.equal(f.service.vault.get('demo'),'super-secret-value');const dbBytes=readFileSync(join(f.dir,'pag.sqlite'));assert.equal(dbBytes.includes(Buffer.from('super-secret-value')),false);assert.equal(JSON.stringify(f.service.vault.list()).includes('super-secret-value'),false)}finally{f.cleanup()}});

test('audit hash chain verifies',async()=>{const f=fixture();try{const {actor}=f.service.createActor('agent');f.service.createGrant({actorId:actor.id,capability:'noop.test',effect:'allow'});await f.service.createIntent({actorId:actor.id,capability:'noop.test',args:{ok:true}});const v=f.service.audit.verify();assert.equal(v.ok,true);assert.ok(v.count>=4)}finally{f.cleanup()}});

test('HTTP actor flow authenticates token and exposes account-scoped browser handoff',async()=>{const f=fixture();let server;try{const {actor,token}=f.service.createActor('publisher');const connection=f.service.createConnection({name:'Personal X',connector:'x',accountLabel:'@me',scopes:['publish']});f.service.setConnectionAccess({actorId:actor.id,connectionId:connection.id,level:'automatic'});server=createServer(f.service,{dir:f.dir});await new Promise(r=>server.listen(0,'127.0.0.1',r));const port=server.address().port;const res=await fetch(`http://127.0.0.1:${port}/v1/intents`,{method:'POST',headers:{authorization:`Bearer ${token}`,'content-type':'application/json','x-pag-idempotency-key':'tweet-1'},body:JSON.stringify({capability:'x.threads.create',args:{text:'Hello from PAG',connectionId:connection.id}})});assert.equal(res.status,201);const data=await res.json();assert.equal(data.status,'succeeded');assert.equal(data.execution.result.autonomous,false);assert.match(data.execution.result.handoffs[0].url,/x\.com\/intent\/tweet/)}finally{if(server)await new Promise(r=>server.close(r));f.cleanup()}});

test('actor token rotation invalidates the old token and revocation fails closed',()=>{const f=fixture();try{const first=f.service.createActor('rotating');assert.equal(f.service.authenticateToken(first.token).id,first.actor.id);const second=f.service.rotateActorToken(first.actor.id);assert.equal(f.service.authenticateToken(first.token),null);assert.equal(f.service.authenticateToken(second.token).id,first.actor.id);f.service.setActorStatus(first.actor.id,'revoked');assert.equal(f.service.authenticateToken(second.token),null)}finally{f.cleanup()}});

test('lockdown overrides an otherwise allowed grant',async()=>{const f=fixture();try{const {actor}=f.service.createActor('agent');f.service.createGrant({actorId:actor.id,capability:'noop.test',effect:'allow',priority:100});f.service.setLockdown(true);const i=await f.service.createIntent({actorId:actor.id,capability:'noop.test',args:{}});assert.equal(i.status,'denied');assert.equal(i.policy_effect,'deny');assert.equal(f.service.summary().lockdown,true);f.service.setLockdown(false);const j=await f.service.createIntent({actorId:actor.id,capability:'noop.test',args:{ok:true}});assert.equal(j.status,'succeeded')}finally{f.cleanup()}});

test('connections are metadata-only references and connector type mismatch is denied before execution',async()=>{const f=fixture();try{f.service.vault.put('social.secret','opaque-cookie',{connector:'x'});const c=f.service.createConnection({name:'Personal X',connector:'x',accountLabel:'@me',vaultRef:'social.secret',scopes:['publish']});assert.equal(c.vault_ref,'social.secret');assert.equal(JSON.stringify(c).includes('opaque-cookie'),false);const {actor}=f.service.createActor('publisher');f.service.setConnectionAccess({actorId:actor.id,connectionId:c.id,level:'automatic'});const i=await f.service.createIntent({actorId:actor.id,capability:'linkedin.posts.create',args:{text:'hello',connectionId:c.id}});assert.equal(i.status,'denied');assert.equal(i.execution,null);const audit=f.service.audit.list(20);assert.ok(audit.some(x=>x.event_type==='intent.denied'&&x.data.reason==='connection_type_mismatch'))}finally{f.cleanup()}});

test('control actor can approve exact pending payload without admin privileges',async()=>{const f=fixture();let server;try{const agent=f.service.createActor('agent');const control=f.service.createActor('WhatsApp Control','control');f.service.createGrant({actorId:agent.actor.id,capability:'noop.test',effect:'ask'});const pending=await f.service.createIntent({actorId:agent.actor.id,capability:'noop.test',args:{task:'publish'}});server=createServer(f.service,{dir:f.dir});await new Promise(r=>server.listen(0,'127.0.0.1',r));const port=server.address().port;const bad=await fetch(`http://127.0.0.1:${port}/v1/control/approvals`,{headers:{authorization:`Bearer ${agent.token}`}});assert.equal(bad.status,401);const list=await fetch(`http://127.0.0.1:${port}/v1/control/approvals`,{headers:{authorization:`Bearer ${control.token}`}});assert.equal(list.status,200);const data=await list.json();assert.equal(data.approvals.length,1);const approved=await fetch(`http://127.0.0.1:${port}/v1/control/approvals/${pending.approval.id}/approve`,{method:'POST',headers:{authorization:`Bearer ${control.token}`,'content-type':'application/json'},body:JSON.stringify({expectedArgsHash:pending.args_hash})});assert.equal(approved.status,200);const result=await approved.json();assert.equal(result.status,'succeeded');const audit=f.service.audit.list(20);assert.ok(audit.some(x=>x.event_type==='approval.approved'&&String(x.actor).startsWith('control:')))}finally{if(server)await new Promise(r=>server.close(r));f.cleanup()}});


test('new agent-account pairs default to explicit no access',()=>{const f=fixture();try{const first=f.service.createActor('first');const c=f.service.createConnection({name:'X',connector:'x',scopes:['read','publish']});assert.equal(f.service.getConnectionAccess(first.actor.id,c.id).level,'none');const second=f.service.createActor('second');assert.equal(f.service.getConnectionAccess(second.actor.id,c.id).level,'none');const matrix=f.service.accessMatrix();assert.equal(matrix.cells.length,2);assert.ok(matrix.cells.every(x=>x.level==='none'))}finally{f.cleanup()}});

test('read, ask, and automatic access levels enforce provider capability modes',async()=>{const f=fixture();try{const {actor}=f.service.createActor('agent');const x=f.service.createConnection({name:'X',connector:'x',scopes:['read','publish']});f.service.setConnectionAccess({actorId:actor.id,connectionId:x.id,level:'read'});const readDecision=f.service._evaluateConnectionAccess(actor.id,'x.posts.inspect',x.id);assert.equal(readDecision.effect,'allow');const writeDenied=await f.service.createIntent({actorId:actor.id,capability:'x.threads.create',args:{text:'no',connectionId:x.id}});assert.equal(writeDenied.status,'denied');f.service.setConnectionAccess({actorId:actor.id,connectionId:x.id,level:'ask'});const pending=await f.service.createIntent({actorId:actor.id,capability:'x.threads.create',args:{text:'ask me',connectionId:x.id}});assert.equal(pending.status,'pending_approval');f.service.setConnectionAccess({actorId:actor.id,connectionId:x.id,level:'automatic'});const auto=await f.service.createIntent({actorId:actor.id,capability:'x.threads.create',args:{text:'go',connectionId:x.id}});assert.equal(auto.status,'succeeded')}finally{f.cleanup()}});

test('account scope downgrade blocks capabilities even when agent access is automatic',async()=>{const f=fixture();try{const {actor}=f.service.createActor('agent');const c=f.service.createConnection({name:'X',connector:'x',scopes:['read','publish']});f.service.setConnectionAccess({actorId:actor.id,connectionId:c.id,level:'automatic'});const before=await f.service.createIntent({actorId:actor.id,capability:'x.threads.create',args:{text:'before',connectionId:c.id}});assert.equal(before.status,'succeeded');const change=f.service.setConnectionScopes(c.id,['read']);assert.deepEqual(change.removed,['publish']);const after=await f.service.createIntent({actorId:actor.id,capability:'x.threads.create',args:{text:'after',connectionId:c.id}});assert.equal(after.status,'denied');const event=f.service.audit.list(20).find(x=>x.event_type==='intent.denied'&&x.subject_id===after.id);assert.equal(event.data.reason,'connection_scope_missing')}finally{f.cleanup()}});

test('downgrading access invalidates a previously pending approval before execution',async()=>{const f=fixture();try{const {actor}=f.service.createActor('agent');const c=f.service.createConnection({name:'X',connector:'x',scopes:['publish']});f.service.setConnectionAccess({actorId:actor.id,connectionId:c.id,level:'ask'});const pending=await f.service.createIntent({actorId:actor.id,capability:'x.threads.create',args:{text:'pending',connectionId:c.id}});assert.equal(pending.status,'pending_approval');f.service.setConnectionAccess({actorId:actor.id,connectionId:c.id,level:'none'});await assert.rejects(()=>f.service.approve(pending.approval.id,{expectedArgsHash:pending.args_hash}),/no longer authorizes/i);const still=f.service.getIntent(pending.id);assert.equal(still.status,'pending_approval');assert.equal(still.approval.state,'pending');assert.equal(still.execution,null)}finally{f.cleanup()}});

test('disconnect preserves connection and audit history while blocking use, then reconnect restores it',async()=>{const f=fixture();try{const {actor}=f.service.createActor('agent');const c=f.service.createConnection({name:'LinkedIn',connector:'linkedin',accountLabel:'Victor',scopes:['publish']});f.service.setConnectionAccess({actorId:actor.id,connectionId:c.id,level:'automatic'});const disconnected=f.service.disconnectConnection(c.id);assert.equal(disconnected.lifecycle,'disconnected');const denied=await f.service.createIntent({actorId:actor.id,capability:'linkedin.posts.create',args:{text:'blocked',connectionId:c.id}});assert.equal(denied.status,'denied');const reconnected=f.service.reconnectConnection(c.id);assert.equal(reconnected.lifecycle,'active');const done=await f.service.createIntent({actorId:actor.id,capability:'linkedin.posts.create',args:{text:'restored',connectionId:c.id}});assert.equal(done.status,'succeeded');const events=f.service.audit.list(50);assert.ok(events.some(x=>x.event_type==='connection.disconnected'&&x.subject_id===c.id));assert.ok(events.some(x=>x.event_type==='connection.reconnected'&&x.subject_id===c.id))}finally{f.cleanup()}});

test('custom connection access can ask for one capability while denying another',async()=>{const f=fixture();try{const {actor}=f.service.createActor('agent');const c=f.service.createConnection({name:'X',connector:'x',scopes:['read','publish']});f.service.setConnectionAccess({actorId:actor.id,connectionId:c.id,level:'custom',capabilities:{'x.posts.inspect':'deny','x.threads.create':'ask'}});const read=await f.service.createIntent({actorId:actor.id,capability:'x.posts.inspect',args:{url:'https://x.com/u/status/123',connectionId:c.id}});assert.equal(read.status,'denied');const write=await f.service.createIntent({actorId:actor.id,capability:'x.threads.create',args:{text:'custom',connectionId:c.id}});assert.equal(write.status,'pending_approval')}finally{f.cleanup()}});


test('admin API exposes providers and can change one matrix cell',async()=>{const f=fixture();let server;try{const actor=f.service.createActor('dashboard-agent');const c=f.service.createConnection({name:'Personal X',connector:'x',scopes:['read','publish']});server=createServer(f.service,{dir:f.dir});await new Promise(r=>server.listen(0,'127.0.0.1',r));const port=server.address().port;const login=await fetch(`http://127.0.0.1:${port}/auth/login`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({token:adminToken(f.dir)})});assert.equal(login.status,200);const cookie=login.headers.get('set-cookie').split(';')[0];const providers=await fetch(`http://127.0.0.1:${port}/v1/providers`,{headers:{cookie}});assert.equal(providers.status,200);const catalog=await providers.json();assert.ok(catalog.providers.some(x=>x.id==='x'));const updated=await fetch(`http://127.0.0.1:${port}/v1/access/${c.id}/${actor.actor.id}`,{method:'PUT',headers:{cookie,'content-type':'application/json','x-pag-csrf':'1'},body:JSON.stringify({level:'ask'})});assert.equal(updated.status,200);const matrix=await fetch(`http://127.0.0.1:${port}/v1/access-matrix`,{headers:{cookie}});assert.equal(matrix.status,200);const data=await matrix.json();assert.equal(data.cells.find(x=>x.connection_id===c.id&&x.actor_id===actor.actor.id).level,'ask')}finally{if(server)await new Promise(r=>server.close(r));f.cleanup()}});

test('v1.0 connection rows migrate additively and default existing agent access to none',()=>{const dir=mkdtempSync(join(tmpdir(),'pag-migrate-'));try{initSecrets(dir);const raw=new DatabaseSync(join(dir,'pag.sqlite'));raw.exec(`CREATE TABLE actors (id TEXT PRIMARY KEY,name TEXT NOT NULL,kind TEXT NOT NULL DEFAULT 'agent',token_hash TEXT UNIQUE,status TEXT NOT NULL DEFAULT 'active',created_at TEXT NOT NULL);CREATE TABLE connections (id TEXT PRIMARY KEY,name TEXT NOT NULL,connector TEXT NOT NULL,account_label TEXT,vault_ref TEXT,status TEXT NOT NULL DEFAULT 'active' CHECK(status IN ('active','disabled')),metadata_json TEXT NOT NULL DEFAULT '{}',created_at TEXT NOT NULL,updated_at TEXT NOT NULL);INSERT INTO actors VALUES('act_old','Old Agent','agent',NULL,'active','2026-09-01T00:00:00Z');INSERT INTO connections VALUES('con_old','Old X','x','@old',NULL,'active','{}','2026-09-01T00:00:00Z','2026-09-01T00:00:00Z');`);raw.close();const db=openDb(dir);const columns=db.prepare('PRAGMA table_info(connections)').all().map(x=>x.name);assert.ok(columns.includes('scopes_json'));assert.ok(columns.includes('disconnected_at'));const access=db.prepare('SELECT * FROM connection_access WHERE actor_id=? AND connection_id=?').get('act_old','con_old');assert.equal(access.level,'none');db.close()}finally{rmSync(dir,{recursive:true,force:true})}});
