import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtempSync, readFileSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { initSecrets } from '../src/config.js';
import { openDb } from '../src/db.js';
import { PagService } from '../src/service.js';
import { createServer } from '../src/server.js';

function fixture(){const dir=mkdtempSync(join(tmpdir(),'pag-test-'));initSecrets(dir);const db=openDb(dir);const service=new PagService(db,{dir});return{dir,db,service,cleanup(){db.close();rmSync(dir,{recursive:true,force:true})}}}

test('default deny blocks ungranted capabilities',async()=>{const f=fixture();try{const {actor}=f.service.createActor('agent');const intent=await f.service.createIntent({actorId:actor.id,capability:'noop.test',args:{a:1}});assert.equal(intent.status,'denied');assert.equal(intent.execution,null)}finally{f.cleanup()}});

test('ask grant binds approval to exact payload and executes once',async()=>{const f=fixture();try{const {actor}=f.service.createActor('agent');f.service.createGrant({actorId:actor.id,capability:'noop.test',effect:'ask'});const intent=await f.service.createIntent({actorId:actor.id,capability:'noop.test',args:{a:1},idempotencyKey:'k1'});assert.equal(intent.status,'pending_approval');assert.ok(intent.approval);await assert.rejects(()=>f.service.approve(intent.approval.id,{expectedArgsHash:'wrong'}),/hash mismatch/i);const done=await f.service.approve(intent.approval.id,{expectedArgsHash:intent.args_hash});assert.equal(done.status,'succeeded');assert.equal(done.execution.result.echo.a,1);const again=await f.service.approve(intent.approval.id,{expectedArgsHash:intent.args_hash});assert.equal(again.execution.id,done.execution.id);const count=f.db.prepare('SELECT COUNT(*) n FROM executions').get().n;assert.equal(Number(count),1)}finally{f.cleanup()}});

test('idempotency keys cannot be rebound to different payloads',async()=>{const f=fixture();try{const {actor}=f.service.createActor('agent');f.service.createGrant({actorId:actor.id,capability:'noop.test',effect:'allow'});const a=await f.service.createIntent({actorId:actor.id,capability:'noop.test',args:{a:1},idempotencyKey:'same'});const b=await f.service.createIntent({actorId:actor.id,capability:'noop.test',args:{a:1},idempotencyKey:'same'});assert.equal(a.id,b.id);await assert.rejects(()=>f.service.createIntent({actorId:actor.id,capability:'noop.test',args:{a:2},idempotencyKey:'same'}),/different arguments/i)}finally{f.cleanup()}});

test('deny at the highest matching priority wins over allow',async()=>{const f=fixture();try{const {actor}=f.service.createActor('agent');f.service.createGrant({actorId:actor.id,capability:'noop.*',effect:'allow',priority:10});f.service.createGrant({actorId:actor.id,capability:'noop.test',effect:'deny',priority:10});const i=await f.service.createIntent({actorId:actor.id,capability:'noop.test',args:{}});assert.equal(i.status,'denied')}finally{f.cleanup()}});

test('vault encrypts secrets and API metadata never returns plaintext',()=>{const f=fixture();try{f.service.vault.put('demo','super-secret-value',{connector:'noop'});assert.equal(f.service.vault.get('demo'),'super-secret-value');const dbBytes=readFileSync(join(f.dir,'pag.sqlite'));assert.equal(dbBytes.includes(Buffer.from('super-secret-value')),false);assert.equal(JSON.stringify(f.service.vault.list()).includes('super-secret-value'),false)}finally{f.cleanup()}});

test('audit hash chain verifies',async()=>{const f=fixture();try{const {actor}=f.service.createActor('agent');f.service.createGrant({actorId:actor.id,capability:'noop.test',effect:'allow'});await f.service.createIntent({actorId:actor.id,capability:'noop.test',args:{ok:true}});const v=f.service.audit.verify();assert.equal(v.ok,true);assert.ok(v.count>=4)}finally{f.cleanup()}});

test('HTTP actor flow authenticates token and exposes approved browser handoff',async()=>{const f=fixture();let server;try{const {actor,token}=f.service.createActor('publisher');f.service.createGrant({actorId:actor.id,capability:'x.threads.create',effect:'allow'});server=createServer(f.service,{dir:f.dir});await new Promise(r=>server.listen(0,'127.0.0.1',r));const port=server.address().port;const res=await fetch(`http://127.0.0.1:${port}/v1/intents`,{method:'POST',headers:{authorization:`Bearer ${token}`,'content-type':'application/json','x-pag-idempotency-key':'tweet-1'},body:JSON.stringify({capability:'x.threads.create',args:{text:'Hello from PAG'}})});assert.equal(res.status,201);const data=await res.json();assert.equal(data.status,'succeeded');assert.equal(data.execution.result.autonomous,false);assert.match(data.execution.result.handoffs[0].url,/x\.com\/intent\/tweet/)}finally{if(server)await new Promise(r=>server.close(r));f.cleanup()}});

test('actor token rotation invalidates the old token and revocation fails closed',()=>{const f=fixture();try{const first=f.service.createActor('rotating');assert.equal(f.service.authenticateToken(first.token).id,first.actor.id);const second=f.service.rotateActorToken(first.actor.id);assert.equal(f.service.authenticateToken(first.token),null);assert.equal(f.service.authenticateToken(second.token).id,first.actor.id);f.service.setActorStatus(first.actor.id,'revoked');assert.equal(f.service.authenticateToken(second.token),null)}finally{f.cleanup()}});

test('lockdown overrides an otherwise allowed grant',async()=>{const f=fixture();try{const {actor}=f.service.createActor('agent');f.service.createGrant({actorId:actor.id,capability:'noop.test',effect:'allow',priority:100});f.service.setLockdown(true);const i=await f.service.createIntent({actorId:actor.id,capability:'noop.test',args:{}});assert.equal(i.status,'denied');assert.equal(i.policy_effect,'deny');assert.equal(f.service.summary().lockdown,true);f.service.setLockdown(false);const j=await f.service.createIntent({actorId:actor.id,capability:'noop.test',args:{ok:true}});assert.equal(j.status,'succeeded')}finally{f.cleanup()}});

test('connections are metadata-only references and connector type is enforced',async()=>{const f=fixture();try{f.service.vault.put('social.secret','opaque-cookie',{connector:'x'});const c=f.service.createConnection({name:'Personal X',connector:'x',accountLabel:'@me',vaultRef:'social.secret'});assert.equal(c.vault_ref,'social.secret');assert.equal(JSON.stringify(c).includes('opaque-cookie'),false);const {actor}=f.service.createActor('publisher');f.service.createGrant({actorId:actor.id,capability:'linkedin.posts.create',effect:'allow'});await assert.rejects(()=>f.service.createIntent({actorId:actor.id,capability:'linkedin.posts.create',args:{text:'hello',connectionId:c.id}}),/not linkedin/i);const i=f.service.listIntentDetails(1)[0];assert.equal(i.status,'failed');assert.match(i.execution.error_text,/not linkedin/i)}finally{f.cleanup()}});

test('control actor can approve exact pending payload without admin privileges',async()=>{const f=fixture();let server;try{const agent=f.service.createActor('agent');const control=f.service.createActor('WhatsApp Control','control');f.service.createGrant({actorId:agent.actor.id,capability:'noop.test',effect:'ask'});const pending=await f.service.createIntent({actorId:agent.actor.id,capability:'noop.test',args:{task:'publish'}});server=createServer(f.service,{dir:f.dir});await new Promise(r=>server.listen(0,'127.0.0.1',r));const port=server.address().port;const bad=await fetch(`http://127.0.0.1:${port}/v1/control/approvals`,{headers:{authorization:`Bearer ${agent.token}`}});assert.equal(bad.status,401);const list=await fetch(`http://127.0.0.1:${port}/v1/control/approvals`,{headers:{authorization:`Bearer ${control.token}`}});assert.equal(list.status,200);const data=await list.json();assert.equal(data.approvals.length,1);const approved=await fetch(`http://127.0.0.1:${port}/v1/control/approvals/${pending.approval.id}/approve`,{method:'POST',headers:{authorization:`Bearer ${control.token}`,'content-type':'application/json'},body:JSON.stringify({expectedArgsHash:pending.args_hash})});assert.equal(approved.status,200);const result=await approved.json();assert.equal(result.status,'succeeded');const audit=f.service.audit.list(20);assert.ok(audit.some(x=>x.event_type==='approval.approved'&&String(x.actor).startsWith('control:')))}finally{if(server)await new Promise(r=>server.close(r));f.cleanup()}});
