import { parseJsonOutput, runOpenCli, openCliDoctor } from './opencli.js';

const INSTAGRAM_APP_ID='936619743392459';
const INSTAGRAM_ALPHABET='ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-_';
const MAX_MEDIA_ID=9223372036854775807n;

function acceptedHost(host,base){return host===base||host===`www.${base}`||host.endsWith(`.${base}`);}
export function shortcodeToMediaId(shortcode){let value=0n;for(const ch of shortcode){const digit=INSTAGRAM_ALPHABET.indexOf(ch);if(digit<0)return null;value=value*64n+BigInt(digit);if(value>MAX_MEDIA_ID)return null;}return value>0n?value.toString():null;}
export function parseInstagramUrl(input){
  let url;try{url=new URL(input);}catch{throw new Error('Invalid URL.');}if(url.protocol!=='https:')throw new Error('Only HTTPS URLs are allowed.');
  const host=url.hostname.toLowerCase();if(!acceptedHost(host,'instagram.com'))throw new Error('Not an Instagram URL.');
  const parts=url.pathname.split('/').filter(Boolean);if(parts.length<2||!['p','reel','tv'].includes(parts[0]))throw new Error('Expected an Instagram /p/, /reel/, or /tv/ URL.');
  const shortcode=parts[1],mediaId=shortcodeToMediaId(shortcode);if(!mediaId)throw new Error('Invalid Instagram shortcode.');return{platform:'instagram',kind:parts[0],shortcode,mediaId,canonicalUrl:`https://www.instagram.com/${parts[0]}/${shortcode}/`};
}
export function parseXUrl(input){
  let url;try{url=new URL(input);}catch{throw new Error('Invalid URL.');}if(url.protocol!=='https:')throw new Error('Only HTTPS URLs are allowed.');
  const host=url.hostname.toLowerCase();if(!(acceptedHost(host,'x.com')||acceptedHost(host,'twitter.com')))throw new Error('Not an X/Twitter URL.');
  const m=url.pathname.match(/^\/([^/]+)\/status\/(\d+)/);if(!m)throw new Error('Expected an X/Twitter /<user>/status/<id> URL.');return{platform:'x',username:m[1],id:m[2],canonicalUrl:`https://x.com/${m[1]}/status/${m[2]}`};
}
export function routeInspectUrl(input){
  let u;try{u=new URL(input);}catch{throw new Error('Invalid URL.');}const host=u.hostname.toLowerCase();
  if(acceptedHost(host,'reddit.com'))throw new Error('Reddit is intentionally unsupported by PAG.');
  if(acceptedHost(host,'instagram.com'))return parseInstagramUrl(input);
  if(acceptedHost(host,'x.com')||acceptedHost(host,'twitter.com'))return parseXUrl(input);
  throw new Error('Unsupported inspect URL. PAG currently supports Instagram and X.');
}
function instagramScript(t){return `(async()=>{const endpoint='/api/v1/media/${t.mediaId}/info/';let response;try{response=await fetch(endpoint,{method:'GET',credentials:'include',headers:{'Accept':'application/json,text/plain,*/*','X-IG-App-ID':'${INSTAGRAM_APP_ID}'}});}catch(error){return{ok:false,error:'NETWORK_ERROR',detail:String(error?.message||error)}}const raw=await response.text();let data=null;try{data=raw?JSON.parse(raw):null}catch{return{ok:false,error:'NON_JSON_RESPONSE',http_status:response.status}}if(!response.ok)return{ok:false,error:response.status===401||response.status===403?'AUTH_REQUIRED':response.status===429?'RATE_LIMITED':'HTTP_ERROR',http_status:response.status,detail:data?.message||''};const item=data?.items?.[0];if(!item)return{ok:false,error:'NO_MEDIA',detail:data?.message||'No media returned'};const widest=c=>{if(!Array.isArray(c))return null;let best=null;for(const x of c){if(!x||typeof x.url!=='string')continue;const width=Number(x.width||0);if(!best||width>best.width)best={width,height:Number(x.height||0),url:x.url}}return best};const norm=(n,index)=>{if(n.media_type===2){const video=widest(n.video_versions),poster=widest(n?.image_versions2?.candidates);return{index,type:'video',width:video?.width||null,height:video?.height||null,url:video?.url||null,poster_url:poster?.url||null,duration_seconds:Number(n.video_duration||0)||null}}const image=widest(n?.image_versions2?.candidates);return{index,type:'image',width:image?.width||null,height:image?.height||null,url:image?.url||null}};const nodes=item.media_type===8&&Array.isArray(item.carousel_media)?item.carousel_media:[item];return{ok:true,platform:'instagram',access:'read',source:'authenticated-browser-session',kind:${JSON.stringify(t.kind)},shortcode:${JSON.stringify(t.shortcode)},media_id:String(item.pk||item.id||${JSON.stringify(t.mediaId)}),canonical_url:${JSON.stringify(t.canonicalUrl)},author:{id:item?.user?.pk?String(item.user.pk):null,username:item?.user?.username||null,full_name:item?.user?.full_name||null,verified:Boolean(item?.user?.is_verified)},caption:item?.caption?.text||'',created_at:item?.taken_at?new Date(Number(item.taken_at)*1000).toISOString():null,stats:{likes:Number(item.like_count||0),comments:Number(item.comment_count||0),plays:Number(item.play_count||item.ig_play_count||0)||null,views:Number(item.view_count||0)||null},media:nodes.map((n,i)=>norm(n,i+1)),ephemeral_media_urls:true}})()`;}
function xScript(t){return `(async()=>{const sleep=ms=>new Promise(r=>setTimeout(r,ms));for(let i=0;i<32&&!document.querySelector('article[data-testid="tweet"]');i++)await sleep(250);const articles=[...document.querySelectorAll('article[data-testid="tweet"]')];const statusLink=(a)=>[...a.querySelectorAll('a[href*="/status/"]')].find(x=>/\/status\/\\d+/.test(x.getAttribute('href')||''));const root=articles.find(a=>(statusLink(a)?.getAttribute('href')||'').includes('/status/${t.id}'))||articles[0];if(!root)return{ok:false,error:'NO_POST',detail:'No tweet article found in authenticated browser'};const num=s=>{if(!s)return 0;const m=String(s).replace(/,/g,'').match(/([0-9]+(?:\\.[0-9]+)?)([KMB])?/i);if(!m)return 0;let n=Number(m[1]);const u=(m[2]||'').toUpperCase();if(u==='K')n*=1e3;if(u==='M')n*=1e6;if(u==='B')n*=1e9;return Math.round(n)};const metric=(a,id)=>{const e=a.querySelector('[data-testid="'+id+'"]');return num(e?.getAttribute('aria-label')||e?.innerText||'')};const one=a=>{const sl=statusLink(a),href=sl?.getAttribute('href')||'';const mm=href.match(/^\/([^/]+)\/status\/(\\d+)/);const txt=a.querySelector('[data-testid="tweetText"]')?.innerText||'';const time=a.querySelector('time')?.getAttribute('datetime')||null;const imgs=[...a.querySelectorAll('img')].map(x=>x.src).filter(x=>/pbs\\.twimg\\.com\/media\//.test(x));const vids=[...a.querySelectorAll('video')].map(v=>v.poster).filter(Boolean);return{id:mm?.[2]||null,canonical_url:mm?('https://x.com/'+mm[1]+'/status/'+mm[2]):null,author:{username:mm?.[1]||null},text:txt,created_at:time,stats:{likes:metric(a,'like'),retweets:metric(a,'retweet')},media:[...new Set([...imgs,...vids])].map((url,i)=>({index:i+1,type:/video/.test(url)?'video':'image',url,poster_url:url}))}};const r=one(root);const replies=articles.filter(a=>a!==root).map(one).filter(x=>x.id&&x.id!==r.id).slice(0,50).map(x=>({id:x.id,canonical_url:x.canonical_url,author:x.author,text:x.text,created_at:x.created_at,stats:x.stats,has_media:x.media.length>0}));return{ok:true,platform:'x',access:'read',source:'authenticated-browser-session',kind:'post',id:r.id||${JSON.stringify(t.id)},canonical_url:${JSON.stringify(t.canonicalUrl)},author:r.author,text:r.text,created_at:r.created_at,stats:r.stats,media:r.media,quoted_post:null,conversation:{replies_returned:replies.length,replies}}})()`;}
function sanitizeMedia(result,registry,sourceUrl){
  if(!registry||!Array.isArray(result?.media))return result;
  result.media=result.media.map(m=>{const out={...m};if(out.url){out.handle=registry.register(out.url,{sourceUrl,role:'media',index:out.index,type:out.type});delete out.url;}if(out.poster_url){out.poster_handle=registry.register(out.poster_url,{sourceUrl,role:'poster',index:out.index,type:out.type});delete out.poster_url;}return out;});result.media_handles=true;result.media_urls_exposed=false;return result;
}
export class Inspector{
  constructor({mediaRegistry,runner=runOpenCli,audit=null}={}){this.mediaRegistry=mediaRegistry;this.runner=runner;this.audit=audit;}
  doctor(){return openCliDoctor();}
  async inspect(inputUrl){const t=routeInspectUrl(inputUrl),session=`pag-${t.platform}-${process.pid}-${Date.now()}`;this.runner(['browser',session,'close'],{allowFailure:true});try{this.runner(['browser',session,'open',t.canonicalUrl]);const script=t.platform==='instagram'?instagramScript(t):xScript(t);const result=this.runner(['browser',session,'eval',script]);const data=parseJsonOutput(result.stdout);if(!data?.ok)throw new Error(`${data?.error||'INSPECT_FAILED'}${data?.detail?`: ${data.detail}`:''}`);sanitizeMedia(data,this.mediaRegistry,t.canonicalUrl);this.audit?.append('local-admin','inspect.completed',t.canonicalUrl,{platform:t.platform});return data;}finally{this.runner(['browser',session,'close'],{allowFailure:true});}}
}
